# Generated by Django 3.0.5 on 2021-04-26 18:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public_id')),
                ('username', models.CharField(blank=True, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Instructor'), (3, 'Player')], default=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'users',
            },
        ),
        migrations.CreateModel(
            name='DemandPattern',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='public_id')),
                ('name', models.CharField(max_length=64)),
                ('weeks', models.IntegerField(validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(8)])),
                ('demand', models.CharField(blank=True, max_length=256)),
                ('related_games', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'verbose_name': 'demand_pattern',
                'verbose_name_plural': 'demand_patterns',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='public_id')),
                ('allowed_games', models.CharField(blank=True, max_length=1024)),
                ('instructors', models.CharField(blank=True, max_length=1024)),
                ('current_game', models.CharField(blank=True, max_length=64)),
                ('inventory', models.IntegerField(default=0)),
                ('backorder', models.IntegerField(default=0)),
                ('downstream_player', models.CharField(blank=True, max_length=64)),
                ('upstream_player', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='base.User')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='public_id')),
                ('games_managing', models.CharField(blank=True, max_length=1024)),
                ('my_players', models.CharField(blank=True, max_length=4096)),
                ('my_plots', models.CharField(blank=True, max_length=4096)),
                ('my_default_game', models.CharField(blank=True, max_length=2048)),
                ('players', models.ManyToManyField(related_name='instructors_players', to='base.Player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='base.User')),
            ],
            options={
                'verbose_name': 'instructor',
                'verbose_name_plural': 'instructors',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='public_id')),
                ('session_length', models.IntegerField(default=0)),
                ('distributor_present', models.BooleanField(default=False)),
                ('wholesaler_present', models.BooleanField(default=False)),
                ('holding_cost', models.FloatField(default=0.0)),
                ('backlog_cost', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=False)),
                ('info_sharing', models.BooleanField(default=False)),
                ('info_delay', models.IntegerField(default=2)),
                ('rounds_completed', models.IntegerField(default=0)),
                ('is_default_game', models.BooleanField(default=False)),
                ('starting_inventory', models.IntegerField(default=12)),
                ('player_weeks', models.CharField(max_length=4)),
                ('demandpattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_demandpattern', to='base.DemandPattern')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors_game', to='base.Instructor')),
                ('player', models.ManyToManyField(related_name='players_game', to='base.Player')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.AddField(
            model_name='demandpattern',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors_demand_pattern', to='base.Instructor'),
        ),
    ]
