# Generated by Django 3.0.5 on 2021-04-23 06:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPattern',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='public_id')),
                ('name', models.CharField(max_length=64)),
                ('weeks', models.IntegerField(validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(8)])),
                ('demand', models.CharField(blank=True, max_length=256)),
                ('related_games', models.CharField(blank=True, max_length=1024)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors_demand_pattern', to='base.Instructor')),
            ],
            options={
                'verbose_name': 'demand_pattern',
                'verbose_name_plural': 'demand_patterns',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='public_id')),
                ('session_length', models.IntegerField(default=0)),
                ('distributor_present', models.BooleanField(default=False)),
                ('wholesaler_present', models.BooleanField(default=False)),
                ('holding_cost', models.FloatField(default=0.0)),
                ('backlog_cost', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=False)),
                ('info_sharing', models.BooleanField(default=False)),
                ('info_delay', models.IntegerField(default=2)),
                ('rounds_completed', models.IntegerField(default=0)),
                ('is_default_game', models.BooleanField(default=False)),
                ('starting_inventory', models.IntegerField(default=12)),
                ('player_weeks', models.CharField(max_length=4)),
                ('demandpattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_demandpattern', to='base.DemandPattern')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors_game', to='base.Instructor')),
                ('player', models.ManyToManyField(related_name='players_game', to='base.Player')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
    ]
